### ISSUE TITLE
Please provide tar with deps - for Gentoo Linux packaging

### ISSUE THREAD

**Issue by vitaly-zdanevich** [yitsushi/totp-cli#125]
Hi, this is sad but in Gentoo for Go packages we need to host deps somewhere... if not in `vendor` Go folder - maybe to Github Action could be added one or two line for that?

See the context here https://github.com/gentoo/guru/commit/23487b9ca561e1d9feca81ca2c1aa6f0cc1ebe90#commitcomment-142489696

**Comment by yitsushi** [comment]
Sorry for the late response. Back in May I put some labels on it in hope of someone can do it. Now I'm on leave with extra time (and I can't sleep) so I tried to tackle it. A few points:

**Vendor directory**

I didn't want to put the vendor directory in the repo as it is, because it would be kinds just spam for the repo itself as it's not used and I have no plans to start using it.

**Local publish**

Sadly hooks for archives are supported only with goreleaser pro, so I had to add an extra step to the workflow itself and tell goreleaser to create an archive from that directory. Because of that, it can't be published from local repo without extra steps. Not that it matters too much, never did it and I never really wanted to do that, but that's a side-effect because of that feature is behind goreleaser pro.

**Packaging**

I loved Gentoo for a very long time, but I'm not using it since... I don't even remember, I think I switch in 2008 or something like that. That's the main reason I decided to pick it up. I do think it's important to get everything ready and authentic as possible for packages, I don't think any open source project maintainer should have the burden of supporting all kind of release processes for different package managers. If someone feels the need to create a new package, they should maintain it and take the burden of maintaining it long term.

It doesn't mean it can't live in the same repo as the project itself, but the maintenance or it shouldn't be the one maintaining the project itself, if they didn't add that feature by themselves.

What I want to say with that, if that stops working for some random reasons:
1. There is no easy way to me to test if it's still good enough.
2. I may not have the time or resources to fix it in short time.
3. New pull requests to update or fix how it work are always welcomed.

I have my own arch package for this project, it's not part of the repo because I can't guarantee I'll keep it up to date with standards and requirements, or fix asap (as I can always just download the binary or build it with `go build` or `go install`).
