### ISSUE TITLE
Add prefix to generated OTP

### ISSUE THREAD

**Issue by Peter2121** [yitsushi/totp-cli#47]
Some accounts use passwords containing a fixed part concatenated with OTP.
Though it is possible to do two copy-paste operations, it would be nice to add a possibility to put a 'prefix' for generated  OTPs at the level of account. So, the generated OTP will be shown as something like this:
`p@ssw0rd463036` where `p@ssw0rd` will be securely stored at the account level at the moment of account creation. A possibility to change such prefix without recreating the account would be even better ;)

**Comment by yitsushi** [comment]
Follow-up: I did not forget it, but still thinking a way to add it as on the back-end side, the storage has a "key=value" structure.

Changing this would break the file format. On a different branch I started to work on a v2 where the storage is completely different and it's v2 because it has a breaking changes and a migration process has to be done (will be provided). So maybe this will land only in v2 only, if I can't find a way to change the structure without breaking (and causing myself a lot of pain to implement) existing storage files.

**Comment by yitsushi** [comment]
@Peter2121: Sorry for the long wait, from version `v1.2.4` (technically `v1.2.3`[^1]), you can use the `set-prefix` to set/change the prefix.

If it does not fit your needs, please let me know and reopen this issue.

[^1]: With `1.2.3`, there was not option to remove a prefix.

**Comment by BrunoKrugel** [comment]
and how to remove a prefix? using a empty space does not work

**Comment by yitsushi** [comment]
> and how to remove a prefix? using a empty space does not work

well that's something I clearly did not think of 😆

**Comment by yitsushi** [comment]
That's funny, I wanted to update the README file and found this:
> To remove the prefix from an account, set the prefix to `-` (and because of that, we can't set the prefix to be `-`).

**Comment by yitsushi** [comment]
@BrunoKrugel : The clear flag is available in `v1.2.6`
