### ISSUE TITLE
Add --help documentation

### ISSUE THREAD

**Issue by jmhertlein** [yitsushi/totp-cli#78]
This is a neat tool, I'm using it to help test an MFA implementation, so I end up having a lot of throw-away codes that otherwise clutter up my authenticator app on my phone. Thank you for your work on it :) 

One small thing I noticed:

Running `--help` yields:

```
$ totp-cli --help
Usage of totp-cli:
```

(this is on ubuntu jammy). 

It'd be nice if this could alias to `totp-cli help` and print the same output, since `--help` is more standard/familiar, I think.

**Comment by yitsushi** [comment]
When I created the library used for the cli interface, I did not add global flags intentionally. They can be useful, but I tried to go with no global functions to see how it works as an experiment. As a result the main command can't have `--help` flag, that's why `totp-cli help` is there.

There is an issue to move from my cli interface to use others like [urfave](https://github.com/yitsushi/totp-cli/issues/39), but until it's done, this can't be closed. Of course I can add this extra feature to [go-commander](https://github.com/yitsushi/go-commander), but that feels wasted efforts.

**Comment by yitsushi** [comment]
Blocked on https://github.com/yitsushi/totp-cli/issues/39

**Comment by yitsushi** [comment]
Fixed :tada: 

```
❯ totp-cli --help
NAME:
   totp-cli - Authy/Google Authenticator like TOTP CLI tool written in Go.

USAGE:
   totp-cli [global options] command [command options] [arguments...]

VERSION:
   v1.4.0

AUTHOR:
   Efertone <efertone@pm.me>

COMMANDS:
   add-token, add   Add new token.
   change-password  Change password.
   delete           Delete an account or a whole namespace.
   dump             Dump all available accounts under all namespaces.
   generate, g      Generate a specific OTP
   import           Import tokens from a yaml file.
   instant          Generate an OTP from TOTP_TOKEN or stdin without the Storage backend.
   list             List all available namespaces or accounts under a namespace.
   set-prefix       Set prefix for a token.
   update           Check and update totp-cli itself
   help, h          Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```
